import{firebaseConfig}from'./firebase-config.js';import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';import{getFirestore,doc,getDoc,setDoc}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let currentUser=null,cloudChecks={},cloudLoaded=false;
window.showWorkspace=n=>{document.getElementById('home').style.display='none';document.querySelectorAll('.workspace').forEach(w=>w.classList.remove('active'));document.getElementById(n).classList.add('active');scrollTo(0,0)};window.showHome=()=>{document.querySelectorAll('.workspace').forEach(w=>w.classList.remove('active'));document.getElementById('home').style.display='grid';scrollTo(0,0)};
const music=[['Venue confirmed','July 11 location locked'],['Flyer for July 11 show','Make and post official flyer'],['Rehearsals with Asaf set','Schedule rehearsals and setlist'],['Promotion for show','Announcement, stories, reels, reminders'],['Finish MuzArt vid 2','Complete edit and post'],['Anybody Anywhere vids out','Release performance clips'],['Book July Show #2','Second July show'],['Book July Show #3','Third July show'],['Book August Show #1','August pipeline'],['Book August Show #2','Second August show'],['Book August Show #3','Third August show'],['Find 5 more venues','Valley/LA venue outreach']];
const venues=[['Venue #1','Ventura Music lead / July 11'],['Venue #2','Valley or LA option'],['Venue #3','Valley or LA option'],['Venue #4','Valley or LA option'],['Venue #5','Valley or LA option'],['Venue #6','Valley or LA option']];
const show=[['Meet venue guy','Talk logistics'],['Date confirmed','July 11 Saturday'],['Start time confirmed','Doors/music time'],['PA / gear confirmed','Know what to bring'],['Lineup finalized','Artists confirmed'],['Flyer finished','Ready to post'],['Announcement posted','Main feed/reel/story'],['Rehearsal complete','Asaf/set ready'],['Film plan confirmed','Vertical + horizontal'],['Post-show recap','Turn show into content']];
const week=[['Complete COPE clearances','Due next week'],['Verify COPE docs submitted','Portal/email'],['Confirm COPE dates','July 11, 12, 18'],['Upload site files to GitHub root','index/style/script/firebase'],['Finish BIO 101 lab','Posts to transcript'],['POLS retake','Target A'],['Confirm Fall registration','Physio + Micro + Soc']];
const matrix=[['English I','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅ Complete',true],['English II','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅ Complete',true],['Statistics','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅ A',true],['Psychology','✅','✅','✅','✅','✅','✅','✅','⭐','✅','✅ Complete',true],['Lifespan Psych','✅','✅','✅','⭐','⭐','⭐','⭐','⭐','⭐','✅ Complete',true],['Public Speaking','⭐','⭐','⭐','✅','✅','✅','✅','⭐','➖','✅ Complete',true],['BIO 101','⭐','⭐','⭐','⭐','⭐','⭐','⭐','➖','➖','✅ after lab posts',false],['BIO 006','➖','➖','➖','➖','➖','➖','➖','✅','✅','✅ Complete',true],['Anatomy','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅ B',true],['Physiology','✅','✅','✅','✅','✅','✅','✅','✅','✅','🟡 Fall 2026',false],['Microbiology','✅','✅','✅','✅','✅','✅','✅','⭐','✅','🟡 Fall 2026',false],['Sociology','⭐','⭐','⭐','✅','✅','✅','⭐','➖','✅','🟡 Fall 2026',false],['CHEM 051','✅','✅','✅','✅','➖','❓','✅','❌','❌','✅ A',true],['CHEM 101','❌','❌','❌','❓','✅','❓','❓','✅','✅','❓ verify',false],['CHEM 102','❌','❌','❌','❌','❌','❌','❌','✅','✅','🔴 not taken',false],['CHEM 211','❌','❌','❌','❌','✅','❌','❌','✅','➖','🔴 not taken',false],['TEAS','✅','✅','✅','⭐','⭐','⭐','⭐','❌','❌','🔴 not taken',false],['COPE','⭐','⭐','⭐','⭐','⭐','⭐','⭐','⭐','⭐','🟡 starts July',false]];
const sem=[['✅ Completed',['English I','English II','Statistics A','Psychology','Lifespan Psych','Public Speaking','BIO 006','Anatomy B','CHEM 051 A']],['☀️ Summer 2026',['COPE clearances by next week','COPE dates: July 11, 12, 18','BIO 101 lab/posting','POLS for A']],['🍂 Fall 2026',['Physiology','Microbiology','Sociology','Continue COPE']],['❄️ Winter 2027',['TEAS prep/take','Resume','Essays','Recommendation planning']],['🌱 Spring 2027',['Apply to Spring-entry ADN programs','Continue COPE','Submit transcripts/TEAS/apps']]];
const dead=[['UCLA','Aug 1','Nov 30/Dec 1','Nursing Supplemental Jan 15','Mar-Apr'],['UCI','Aug 1','Nov 30/Dec 1','None','Mar-Apr'],['CSULB','Aug 1','Nov 30','Nursing app + requirements','Spring'],['CSUF','Aug 1','Nov 30','Program requirements','Spring'],['CSULA','Aug 1','Nov 30','NursingCAS Jan 15','Spring'],['CSUCI','Aug 1','Nov 30','Program requirements','Spring'],['Pierce ADN','Sep 15/Feb 15','Oct 1/Mar 1','TEAS/transcripts/app','Nov-Dec/May-Jun'],['Valley ADN','Sept/Apr 1','Late Sept/Apr 30','TEAS/eval/transcripts','After cycle'],['LA City ADN','Jul 15/Jan-Feb','Aug 15/varies','TEAS/info/transcripts','After cycle']];
function localSaved(id,f=false){return localStorage.getItem(id)===null?f:localStorage.getItem(id)==='true'}function saved(id,f=false){return currentUser&&cloudLoaded?(cloudChecks[id]===undefined?f:cloudChecks[id]===true):localSaved(id,f)}function cb(id,f=false,g='school'){return`<input class='task ${g}' type='checkbox' data-id='${id}' data-group='${g}' ${saved(id,f)?'checked':''}>`}
function cards(el,data,prefix,g){document.getElementById(el).innerHTML=data.map((t,i)=>`<div class='task'>${cb(prefix+i,false,g)}<div><strong>${t[0]}</strong><small>${t[1]}</small></div></div>`).join('')}
function render(){cards('musicTasks',music,'musicTask','music');cards('venueTasks',venues,'venue','music');cards('showTasks',show,'show','music');cards('schoolWeek',week,'week','school');document.getElementById('matrixRows').innerHTML=matrix.map((r,i)=>`<tr><td>${cb('matrix'+i,r[10],'school')}</td><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td><td>${r[6]}</td><td>${r[7]}</td><td>${r[8]}</td><td>${r[9]}</td><td>${r[10]}</td></tr>`).join('');document.getElementById('semesterRows').innerHTML=sem.map((s,si)=>`<div class='sem'><h3>${s[0]}</h3>${s[1].map((it,ii)=>`<p>${cb('sem'+si+'_'+ii,s[0].includes('Completed'),'school')} ${it}</p>`).join('')}</div>`).join('');document.getElementById('deadlineRows').innerHTML=dead.map((d,i)=>`<tr><td>${cb('dead'+i,false,'school')}</td><td>${d[0]}</td><td>${d[1]}</td><td>${d[2]}</td><td>${d[3]}</td><td>${d[4]}</td></tr>`).join('');document.querySelectorAll('.task').forEach(b=>b.onchange=async()=>{if(currentUser){cloudChecks[b.dataset.id]=b.checked;await saveCloud()}else localStorage.setItem(b.dataset.id,b.checked);updateCount()});updateCount()}
async function saveCloud(){if(currentUser)await setDoc(doc(db,'roadmaps',currentUser.uid),{checks:cloudChecks,updatedAt:new Date().toISOString()},{merge:true})}async function loadCloud(){if(!currentUser)return;let s=await getDoc(doc(db,'roadmaps',currentUser.uid));cloudChecks=s.exists()&&s.data().checks?s.data().checks:{};cloudLoaded=true}
function updateCount(){['music','school'].forEach(g=>{let b=[...document.querySelectorAll('.task.'+g)],d=b.filter(x=>x.checked).length,t=b.length;document.getElementById(g+'Done').textContent=d;document.getElementById(g+'Total').textContent=t;document.getElementById(g+'Bar').style.width=t?(d/t*100)+'%':'0%'})}
document.getElementById('signInBtn').onclick=()=>signInWithPopup(auth,new GoogleAuthProvider());document.getElementById('signOutBtn').onclick=()=>signOut(auth);onAuthStateChanged(auth,async u=>{currentUser=u;cloudLoaded=false;if(u){signInBtn.style.display='none';signOutBtn.style.display='inline-block';userStatus.textContent='Signed in as '+u.email;render();await loadCloud();render()}else{signInBtn.style.display='inline-block';signOutBtn.style.display='none';userStatus.textContent='Not signed in — saves on this device only.';cloudChecks={};render()}});
