import{firebaseConfig}from'./firebase-config.js';import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';import{getFirestore,doc,getDoc,setDoc}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let currentUser=null,cloudChecks={},cloudLoaded=false;
window.showScreen=id=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');scrollTo(0,0)};window.goHome=()=>showScreen('home');
const data={
quarterGoals:[['Play 9 shows','3 July, 3 August, 3 September'],['Release 3 songs','One per month'],['Find 5 new venues','Valley / LA'],['Meet 25 musicians','Build network'],['Post 60 IG reels/posts','Content engine'],['Book October shows','Before September ends']],
julyLive:[['July 11 show','Ventura Music lead'],['July Show #2','Book and confirm'],['July Show #3','Book and confirm'],['Flyer','Make and post'],['Rehearsal with Asaf','Schedule and setlist'],['Promotion','Countdown, reels, stories']],
julyStudio:[['Release Song #1','First of 3'],['Artwork','Cover/visual'],['Promo reel','Short promo'],['Release post','Day-of post']],
julyPromo:[['MuzArt Video #2','Short-term goal'],['Anybody Anywhere #1','Release clip'],['Anybody Anywhere #2','Release clip'],['Anybody Anywhere #3','Release clip'],['Post-show recap','July 11 content']],
augustLive:[['August Show #1','Book and confirm'],['August Show #2','Book and confirm'],['August Show #3','Book and confirm']],
augustStudio:[['Release Song #2','Second of 3'],['Artwork','Cover/visual'],['Promo reel','Short promo'],['Release post','Day-of post']],
augustPromo:[['August campaign','Promote shows/song'],['Visit 3 venues','In person'],['Lock September venues','Pipeline']],
septemberLive:[['September Show #1','Book and confirm'],['September Show #2','Book and confirm'],['September Show #3','Book and confirm']],
septemberStudio:[['Release Song #3','Third of 3'],['Artwork','Cover/visual'],['Promo reel','Short promo'],['Release post','Day-of post']],
septemberPromo:[['September campaign','Promote shows/song'],['Book October shows','Next pipeline'],['Quarter recap','Summarize growth']],
calendarTasks:[['July 11 show','Add time/location'],['Song #1 release date','Choose date'],['August shows','Add as booked'],['Song #2 release date','Choose date'],['September shows','Add as booked'],['Song #3 release date','Choose date']],
contactTasks:[['Venue contacts','Owners/bookers'],['Musicians met','Names + IG'],['Photographers','People to film'],['Promoters','People running shows'],['Follow-up list','48 hour rule']],
moneyTasks:[['Track show pay','Per gig'],['Track merch','Sales'],['Track expenses','Gas, flyers, rentals'],['Monthly total','Profit/loss']],
schoolWeek:[['Complete COPE clearances','Due next week'],['Verify COPE docs submitted','Portal/email'],['Attend COPE July 11','COPE'],['Attend COPE July 12','COPE'],['Attend COPE July 18','COPE'],['Finish BIO 101 lab','Transcript posting'],['Retake POLS','Target A'],['Register Physiology','Fall 2026'],['Register Microbiology','Fall 2026'],['Register Sociology','Fall 2026']]
};
const venues=[['Current lead','Ventura Music','Meeting / interested'],['Venue #2','Valley / LA','Find contact + message'],['Venue #3','Valley / LA','Find contact + message'],['Venue #4','Valley / LA','Find contact + message'],['Venue #5','Valley / LA','Find contact + message'],['Venue #6','Valley / LA','Find contact + message']];
const songs=[['Song #1','July release','Writing → Recording → Mixing → Mastering → Released'],['Song #2','August release','Writing → Recording → Mixing → Mastering → Released'],['Song #3','September release','Writing → Recording → Mixing → Mastering → Released']];
const matrix=[['English I','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅ Complete',true],['English II','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅ Complete',true],['Statistics','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅ A',true],['Psychology','✅','✅','✅','✅','✅','✅','✅','✅','⭐','✅','✅ Complete',true],['Anatomy','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅ B',true],['Physiology','✅','✅','✅','✅','✅','✅','✅','✅','✅','✅','🟡 Fall 2026',false],['Microbiology','✅','✅','✅','✅','✅','✅','✅','✅','⭐','✅','🟡 Fall 2026',false],['Sociology','⭐','⭐','⭐','⭐','✅','✅','✅','⭐','➖','✅','🟡 Fall 2026',false],['TEAS','✅','✅','✅','⭐','⭐','⭐','⭐','⭐','❌','❌','🔴 not taken',false],['COPE','⭐','⭐','⭐','⭐','⭐','⭐','⭐','⭐','⭐','⭐','🟡 starts July',false]];
const sem=[['✅ Completed',['English I','English II','Statistics A','Psychology','BIO 006','Anatomy B','CHEM 051 A']],['☀️ Summer 2026',['COPE clearances','COPE July 11/12/18','BIO 101 lab','POLS retake']],['🍂 Fall 2026',['Physiology','Microbiology','Sociology','Continue COPE']],['❄️ Winter 2027',['TEAS','Resume','Essays']],['🌱 Spring 2027',['Apply to Spring-entry ADN programs','Submit transcripts/TEAS/apps']]];
const dead=[['UCLA','Aug 1','Nov 30/Dec 1','Supplemental Jan 15','Mar-Apr'],['UCI','Aug 1','Nov 30/Dec 1','None','Mar-Apr'],['CSULB','Aug 1','Nov 30','Nursing app','Spring'],['CSUF','Aug 1','Nov 30','Program requirements','Spring'],['CSULA','Aug 1','Nov 30','NursingCAS Jan 15','Spring'],['CSUCI','Aug 1','Nov 30','Program requirements','Spring'],['Pierce ADN','Sep 15/Feb 15','Oct 1/Mar 1','TEAS/transcripts/app','Nov-Dec/May-Jun']];
function localSaved(id,f=false){return localStorage.getItem(id)===null?f:localStorage.getItem(id)==='true'}function saved(id,f=false){return currentUser&&cloudLoaded?(cloudChecks[id]===undefined?f:cloudChecks[id]===true):localSaved(id,f)}function cb(id,f=false,g='school'){return`<input class='task ${g}' type='checkbox' data-id='${id}' ${saved(id,f)?'checked':''}>`}function cards(el,arr,prefix,g,monthly=''){document.getElementById(el).innerHTML=arr.map((t,i)=>`<div class='task-card'>${cb(prefix+i,false,g+' '+monthly)}<div><strong>${t[0]}</strong><span>${t[1]}</span></div></div>`).join('')}
function render(){['quarterGoals','julyLive','julyStudio','julyPromo','augustLive','augustStudio','augustPromo','septemberLive','septemberStudio','septemberPromo','calendarTasks','contactTasks','moneyTasks'].forEach(k=>cards(k,data[k],k,'music',k.includes('july')?'july':k.includes('august')?'august':k.includes('september')?'september':''));document.getElementById('venueCards').innerHTML=venues.map((v,i)=>`<div class='venue-card'><h3>${v[0]}</h3><p><b>${v[1]}</b></p><p>${v[2]}</p><p>${cb('venueContact'+i,false,'music')} Contacted</p><p>${cb('venueInterested'+i,false,'music')} Interested</p><p>${cb('venueBooked'+i,false,'music')} Booked</p></div>`).join('');document.getElementById('songCards').innerHTML=songs.map((s,i)=>`<div class='song-card'><h3>${s[0]}</h3><p>${s[1]}</p><p>${s[2]}</p><p>${cb('songWrite'+i,false,'music')} Writing done</p><p>${cb('songRec'+i,false,'music')} Recorded</p><p>${cb('songMix'+i,false,'music')} Mixed</p><p>${cb('songMaster'+i,false,'music')} Mastered</p><p>${cb('songRel'+i,false,'music')} Released</p></div>`).join('');cards('schoolWeek',data.schoolWeek,'schoolWeek','school');document.getElementById('matrixRows').innerHTML=matrix.map((r,i)=>`<tr><td>${cb('matrix'+i,r[11],'school')}</td><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td><td>${r[6]}</td><td>${r[7]}</td><td>${r[8]}</td><td>${r[9]}</td><td>${r[10]}</td><td>${r[11]}</td></tr>`).join('');document.getElementById('semesterRows').innerHTML=sem.map((s,si)=>`<div class='semester'><h3>${s[0]}</h3>${s[1].map((it,ii)=>`<p>${cb('sem'+si+'_'+ii,s[0].includes('Completed'),'school')} ${it}</p>`).join('')}</div>`).join('');document.getElementById('deadlineRows').innerHTML=dead.map((d,i)=>`<tr><td>${cb('dead'+i,false,'school')}</td><td>${d[0]}</td><td>${d[1]}</td><td>${d[2]}</td><td>${d[3]}</td><td>${d[4]}</td></tr>`).join('');document.querySelectorAll('.task').forEach(b=>b.onchange=async()=>{if(currentUser){cloudChecks[b.dataset.id]=b.checked;await saveCloud()}else localStorage.setItem(b.dataset.id,b.checked);updateCount()});updateCount()}
async function saveCloud(){if(currentUser)await setDoc(doc(db,'roadmaps',currentUser.uid),{checks:cloudChecks,updatedAt:new Date().toISOString()},{merge:true})}async function loadCloud(){if(!currentUser)return;let s=await getDoc(doc(db,'roadmaps',currentUser.uid));cloudChecks=s.exists()&&s.data().checks?s.data().checks:{};cloudLoaded=true}
function count(sel,doneId,totalId,barId){let b=[...document.querySelectorAll(sel)],d=b.filter(x=>x.checked).length,t=b.length;if(document.getElementById(doneId)){document.getElementById(doneId).textContent=d;document.getElementById(totalId).textContent=t;document.getElementById(barId).style.width=t?(d/t*100)+'%':'0%'}}
function updateCount(){count('.task.music','musicDone','musicTotal','musicBar');count('.task.school','schoolDone','schoolTotal','schoolBar');count('.task.july','julyDone','julyTotal','julyBar');count('.task.august','augustDone','augustTotal','augustBar');count('.task.september','septemberDone','septemberTotal','septemberBar')}
signInBtn.onclick=()=>signInWithPopup(auth,new GoogleAuthProvider());signOutBtn.onclick=()=>signOut(auth);onAuthStateChanged(auth,async u=>{currentUser=u;cloudLoaded=false;if(u){signInBtn.classList.add('hidden');signOutBtn.classList.remove('hidden');userStatus.textContent='Signed in as '+u.email;render();await loadCloud();render()}else{signInBtn.classList.remove('hidden');signOutBtn.classList.add('hidden');userStatus.textContent='Not signed in — saves on this device only.';cloudChecks={};render()}});
